#!/bin/sh

go test ./internal/... ./pkg/... -v

if [ ! -f $GOPATH/bin/golangci-lint ]; then
    echo "FAIL - golangci-lint lionter not found"
    exit 1
fi

$GOPATH/bin/golangci-lint --timeout 5m run ./internal/... ./pkg/... ./cmd/...